
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.performance.analysis.pojo

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

  datasource:
    username: root
    password: g8#6vod3
    url: 'jdbc:mysql://192.168.58.5:3306/performance_analysis'
    driver-class-name: com.mysql.jdbc.Driver
