
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.performance.analysis.pojo
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    efault-statement-timeout: 30
    auto-mapping-unknown-column-behavior: WARNING

spring:
  thymeleaf:
    cache: false
    enabled: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

  datasource:
    username: root
    password: g8#6vod3
    url: 'jdbc:mysql://192.168.58.5:3306/performance_analysis'
    driver-class-name: com.mysql.jdbc.Driver
