
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.performance.analysis.pojo
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    auto-mapping-unknown-column-behavior: WARNING

spring:
  thymeleaf:
    cache: false
    enabled: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

  datasource:
    username:
    password:
    url: 'jdbc:sqlite::resource:performance_analysis.db'
    driver-class-name: org.sqlite.JDBC
